routes:
  /membership/: members/membership
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /:
    data: page.home
    template:
      - home
      # - home-image-right
      # - home-image-circle
      # - home-image-center
      # - home-image-wide
      # - home-image-full
  /archive/:
    template: archive

collections:
  /blog/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/